### ISSUE TITLE
EHM! footer EHM!

### ISSUE THREAD

**Issue by ilyaasha24** [2019Ganjil-PemrogramanBerbasisWeb/tugas2-web-sieg#10]
![image](https://user-images.githubusercontent.com/55181949/67147639-c1c3fb80-f2c0-11e9-90de-ff7132db5bcb.png)

**Comment by bagasimmanuel** [comment]
![FooterFix](https://user-images.githubusercontent.com/55182200/67181847-f5f60400-f407-11e9-902f-c95f45d5eab7.png)
Sudah Fixed
