### ISSUE TITLE
Tidak bisa login

### ISSUE THREAD

**Issue by Rinnabel** [2019Ganjil-PemrogramanBerbasisWeb/tugas2-web-sieg#12]
Setelah daftar kembali ke halaman awal, dikira udah login eh ternyata belom. terus coba login tapi gabisa, padahal udah masuk ke database :(

**Comment by bagasimmanuel** [comment]
Sudah Bisa Mungkin jangan dicoba di Localhost downlaod sendiri, mungkin belum terupdate
![Untitled](https://user-images.githubusercontent.com/55182200/68190562-39dc3200-ffe0-11e9-9681-6f0a779cf7b6.png)
