### ISSUE TITLE
Saran dialihkan ke login/register 

### ISSUE THREAD

**Issue by Rezaaisyi** [2019Ganjil-PemrogramanBerbasisWeb/tugas2-web-sieg#14]
![image](https://user-images.githubusercontent.com/55181853/68220815-f8b54380-001a-11ea-89d9-b117703893cf.png)
Selamat malam kawan!!! saya punya sedikit saran mungkin untuk tombol yang diatas ketika belum punya akun bisa dialihkan ke register atau login. Terima kasih

**Comment by bagasimmanuel** [comment]
Siap Komandan

**Comment by bagasimmanuel** [comment]
Untuk saat ini Bila Belum Login, Maka Bag tidak dapat diakses/tidak terlihat, apabila sudah Login baru muncul Icon Bag disebelah Icon Search
