### ISSUE TITLE
Bug di Gambar

### ISSUE THREAD

**Issue by DSlite** [2019Ganjil-PemrogramanBerbasisWeb/tugas2-web-sieg#2]
Untuk page category, gambarnya masih belum ke load, kalo ku buka linknya, dia "object not found". Mangat rekkk!
![image](https://user-images.githubusercontent.com/17781660/66972768-dab18e80-f0bf-11e9-9eb2-9f58516c6c89.png)
![image](https://user-images.githubusercontent.com/17781660/66972786-e735e700-f0bf-11e9-92e9-938e1347054b.png)

**Comment by fvldi** [comment]
Udah sekut din gambarna, tanks for your issue gan!
![image](https://user-images.githubusercontent.com/55771340/67091327-8ea53d80-f1d6-11e9-8c0a-23b89a241300.png)

**Comment by DSlite** [comment]
Mantap, kalo gitu issuenya ku close aja ya :v
