### ISSUE TITLE
Masalah Database

### ISSUE THREAD

**Issue by DSlite** [2019Ganjil-PemrogramanBerbasisWeb/tugas2-web-sieg#3]
Page login masih belum terkoneksi databse, kayaknya database nya belum di import dari local.
![image](https://user-images.githubusercontent.com/17781660/66972895-44ca3380-f0c0-11e9-8d52-11521fe169c5.png)

**Comment by bagasimmanuel** [comment]
bisa dicoba lagi gan udah fix
