### ISSUE TITLE
Filter Price masih belum berfungsi

### ISSUE THREAD

**Issue by IfaizulHasan** [2019Ganjil-PemrogramanBerbasisWeb/tugas2-web-sieg#6]
sudah dicoba digeser geser namun tampilan tetap sama

**Comment by bagasimmanuel** [comment]
Untuk saat Ini Feature Filter Price dihilangkan terlebih dahulu 
![image](https://user-images.githubusercontent.com/55182200/68191194-925fff00-ffe1-11e9-806d-3ad35dd8daf5.png)
