### ISSUE TITLE
Input BUG pada single-product.php

### ISSUE THREAD

**Issue by Senivri** [2019Ganjil-PemrogramanBerbasisWeb/tugas2-web-sieg#9]
Bisa diinput dengan angka Minus (-) dan Alfabet

![Screenshot 2019-10-17 15 04 24](https://user-images.githubusercontent.com/55181810/66989983-8c1be880-f0ef-11e9-96ae-6186c456922b.png)

**Comment by bagasimmanuel** [comment]
Untuk saat ini Feature Single Product dihilangkan terlebih dahulu
